services:
  mysql:
    build:
      context: ./mysql
    volumes:
      - mysql_data:/var/lib/mysql
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - custom_network

  wordpress:
    depends_on:
      - mysql
    build:
      context: ./wordpress
    container_name: wordpress_container
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    ports:
      - "8000:80"
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - custom_network

volumes:
  mysql_data: 
  wordpress_volume:

networks:
  custom_network:
