version: '3.8'

services:
  wordpress:
    build:
      context: ./wordpress
    container_name: wordpress-container
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: mariadb-container:3306
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: secure_password
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb

  mariadb:
    build:
      context: ./mariadb
    container_name: mariadb-container
    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: wordpress_db
      MARIADB_USER: wordpress_user
      MARIADB_PASSWORD: secure_password
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  wordpress_data:
  mariadb_data:
