name: Azure Static Web Apps CI/CD (Production)

on:
  push:
    branches:
      - release

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      working-directory: Lab2
      run: npm install

    - name: Run tests
      working-directory: Lab2
      run: npm test

    - name: Deploy to Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        app_location: "Lab2/"           # Verzeichnis mit der Anwendung
        output_location: ""             # Kein Build-Ausgabeverzeichnis erforderlich
        deployment_action: "upload"     # Stellt sicher, dass die Dateien hochgeladen werden
